// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package app

import (
	"github.com/cozyo/internal/app/router"
)

// Injectors from wire.go:

// BuildInjector 生成注入器
func BuildInjector() (*Injector, func(), error) {
	auther, cleanup, err := InitAuth()
	if err != nil {
		return nil, nil, err
	}
	routerRouter := &router.Router{
		Auth: auther,
	}
	engine := router.InitWebEngine(routerRouter)
	db, cleanup2, err := InitGormDB()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	injector := &Injector{
		Engine: engine,
		Auth:   auther,
		gorm:   db,
	}
	return injector, func() {
		cleanup2()
		cleanup()
	}, nil
}
